#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-tzinfo
Version  : 1.2.2
Release  : 6
URL      : https://rubygems.org/downloads/tzinfo-1.2.2.gem
Source0  : https://rubygems.org/downloads/tzinfo-1.2.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-thread_safe

%description
TZInfo - Ruby Timezone Library
==============================
[![Gem Version](https://badge.fury.io/rb/tzinfo.svg)](http://badge.fury.io/rb/tzinfo) [![Build Status](https://travis-ci.org/tzinfo/tzinfo.svg?branch=master)](https://travis-ci.org/tzinfo/tzinfo)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n tzinfo-1.2.2
gem spec %{SOURCE0} -l --ruby > rubygem-tzinfo.gemspec

%build
gem build rubygem-tzinfo.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
tzinfo-1.2.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/tzinfo-1.2.2 &&  rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/tzinfo-1.2.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/AmbiguousTime/cdesc-AmbiguousTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/_load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/all-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/all_codes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/cdesc-Country.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/data_source-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/init_countries-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/zone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/zone_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/zone_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Country/zones-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryIndexDefinition/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryIndexDefinition/cdesc-CountryIndexDefinition.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/cdesc-CountryInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/raise_not_implemented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/zone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryInfo/zones-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/cdesc-CountryTimezone.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/description_or_friendly_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/latitude-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/longitude-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/new%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/CountryTimezone/timezone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/cdesc-DataSource.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/country_codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/create_default_data_source-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/data_timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/linked_timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/load_country_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/load_timezone_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/raise_invalid_data_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/set-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSource/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataSourceNotFound/cdesc-DataSourceNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezone/cdesc-DataTimezone.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezoneInfo/cdesc-DataTimezoneInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezoneInfo/create_timezone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezoneInfo/period_for_utc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezoneInfo/periods_for_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezoneInfo/raise_not_implemented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/DataTimezoneInfo/transitions_up_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/InfoTimezone/cdesc-InfoTimezone.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/InvalidCountryCode/cdesc-InvalidCountryCode.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/InvalidDataSource/cdesc-InvalidDataSource.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/InvalidTimezoneIdentifier/cdesc-InvalidTimezoneIdentifier.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/InvalidZoneinfoDirectory/cdesc-InvalidZoneinfoDirectory.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/InvalidZoneinfoFile/cdesc-InvalidZoneinfoFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/LinkedTimezone/cdesc-LinkedTimezone.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/LinkedTimezoneInfo/cdesc-LinkedTimezoneInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/LinkedTimezoneInfo/create_timezone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/LinkedTimezoneInfo/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/LinkedTimezoneInfo/link_to_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/LinkedTimezoneInfo/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/NoOffsetsDefined/cdesc-NoOffsetsDefined.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/OffsetRationals/cdesc-OffsetRationals.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/PeriodNotFound/cdesc-PeriodNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyCoreSupport/cdesc-RubyCoreSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyCountryInfo/Zones/cdesc-Zones.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyCountryInfo/cdesc-RubyCountryInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/cdesc-RubyDataSource.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/country_codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/data_timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/linked_timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/load_country_index-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/load_country_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/load_country_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/load_timezone_index-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/load_timezone_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/load_timezone_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/require_data-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/require_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/require_definition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/require_index-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/RubyDataSource/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/%2b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/%2d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/add_with_convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/cdesc-TimeOrDateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/day-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/hour-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/mday-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/min-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/mon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/month-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/sec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/to_datetime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/to_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/to_orig-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/to_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/usec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/wrap-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimeOrDateTime/year-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/_load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_country_zone_identifiers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_country_zones-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_data_zone_identifiers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_data_zones-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_identifiers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_linked_zone_identifiers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/all_linked_zones-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/canonical_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/canonical_zone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/cdesc-Timezone.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/current_period-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/current_period_and_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/current_time_and_period-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/data_source-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/default_dst%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/default_dst-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/friendly_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/get_proxies-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/get_proxy-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/init_loaded_zones-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/local_to_utc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/now-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/offsets_up_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/period_for_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/period_for_utc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/periods_for_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/raise_unknown_timezone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/strftime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/transitions_up_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/us_zone_identifiers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/us_zones-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/Timezone/utc_to_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneDefinition/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneDefinition/cdesc-TimezoneDefinition.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneIndexDefinition/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneIndexDefinition/cdesc-TimezoneIndexDefinition.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneInfo/cdesc-TimezoneInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneInfo/create_timezone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneInfo/identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneInfo/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneInfo/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneInfo/raise_not_implemented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/abbreviation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/cdesc-TimezoneOffset.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/dst%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/std_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/to_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/to_utc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/utc_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneOffset/utc_total_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/abbreviation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/cdesc-TimezonePeriod.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/dst%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/end_transition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/local_after_start%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/local_before_end%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/local_end-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/local_end_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/local_start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/local_start_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/start_transition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/std_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/to_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/to_utc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_after_start%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_before_end%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_end-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_end_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_start_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_total_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/utc_total_offset_rational-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/valid_for_local%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/valid_for_utc%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezonePeriod/zone_identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/_load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/canonical_zone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/cdesc-TimezoneProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/identifier-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/period_for_utc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/periods_for_local-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/real_timezone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneProxy/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/cdesc-TimezoneTransition.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/datetime-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/local_end-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/local_end_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/local_end_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/local_start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/local_start_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/local_start_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/previous_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/raise_not_implemented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransition/time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TimezoneTransitionDefinition/cdesc-TimezoneTransitionDefinition.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/TransitionDataTimezoneInfo/cdesc-TransitionDataTimezoneInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/UnknownTimezone/cdesc-UnknownTimezone.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoCountryInfo/cdesc-ZoneinfoCountryInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/alternate_iso3166_tab_search_path%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/alternate_iso3166_tab_search_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/cdesc-ZoneinfoDataSource.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/country_codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/data_timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/dms_to_rational-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/enum_timezones-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/find_zoneinfo_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/linked_timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/load_country_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/load_country_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/load_timezone_index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/load_timezone_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/process_search_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/resolve_tab_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/search_path%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/search_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/timezone_identifiers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/validate_zoneinfo_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDataSource/zoneinfo_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoDirectoryNotFound/cdesc-ZoneinfoDirectoryNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/ZoneinfoTimezoneInfo/cdesc-ZoneinfoTimezoneInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/TZInfo/cdesc-TZInfo.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/page-CHANGES_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/tzinfo-1.2.2/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/CHANGES.md
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country_index_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/country_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/data_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/data_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/info_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/linked_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/linked_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/offset_rationals.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/ruby_core_support.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/ruby_country_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/ruby_data_source.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/time_or_datetime.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_index_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_offset.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_period.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_transition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_transition_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/transition_data_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/zoneinfo_country_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/zoneinfo_data_source.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/lib/tzinfo/zoneinfo_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_country.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_country_index_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_country_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_country_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_data_source.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_data_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_data_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_info_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_linked_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_linked_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_offset_rationals.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_ruby_core_support.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_ruby_country_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_ruby_data_source.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_time_or_datetime.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_index_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_london.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_melbourne.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_new_york.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_offset.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_period.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_proxy.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_transition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_transition_definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_timezone_utc.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_transition_data_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_zoneinfo_country_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_zoneinfo_data_source.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tc_zoneinfo_timezone_info.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/test_utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/ts_all.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/ts_all_ruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/ts_all_zoneinfo.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/America/Argentina/Buenos_Aires.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/America/New_York.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Australia/Melbourne.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/EST.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Etc/GMT__m__1.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Etc/GMT__p__1.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Etc/UTC.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Europe/Amsterdam.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Europe/Andorra.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Europe/London.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Europe/Paris.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/Europe/Prague.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/definitions/UTC.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/indexes/countries.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/indexes/timezones.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/tzinfo-data/tzinfo/data/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/America/Argentina/Buenos_Aires
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/America/New_York
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Australia/Melbourne
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/EST
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Etc/UTC
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Europe/Amsterdam
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Europe/Andorra
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Europe/London
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Europe/Paris
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Europe/Prague
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/Factory
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/UTC
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/iso3166.tab
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/localtime
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/posix/Europe/London
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/posixrules
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/right/Europe/London
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/zone.tab
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/test/zoneinfo/zone1970.tab
/usr/lib64/ruby/gems/2.2.0/gems/tzinfo-1.2.2/tzinfo.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/tzinfo-1.2.2.gemspec
